# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '18120254' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 18120254
    pod 'RealmSwift'
    pod 'IGColorPicker'

end
